returns:
  columns:
    run: 0
    step: 0
    episode: 0
    reward: 0.0
    reward_normalized: 0.0
  primary_keys: [run, step]

summary:
  columns:
    run: 0
    step: 0
    episode: 0
    auc100: 0.0
    norm_auc100: 0.0
    auc50: 0.0
    norm_auc50: 0.0
    auc10: 0.0
    norm_auc10: 0.0
    last_score: 0.0
    time_taken: 0.0
  primary_keys: [run]
