defaults:
  - db: credentials-local
  - schema: policy-schema
  - agent: iql
  - _self_

run: 0
db_prefix: lingwei
db_name: unifloral
seed: 0
dataset: halfcheetah-medium-v2
num_updates: 1000000
eval_interval: 2500
eval_workers: 8
eval_final_episodes: 1000
log: false
wandb_project: unifloral
wandb_team: flair
wandb_group: debug

hydra:
  mode: MULTIRUN
  job:
    chdir: false
  sweeper:
    params:
      seed: range(0,5)
      dataset: halfcheetah-medium-expert-v2, halfcheetah-medium-replay-v2, halfcheetah-medium-v2, walker2d-medium-expert-v2, walker2d-medium-replay-v2, walker2d-medium-v2, hopper-medium-replay-v2, hopper-medium-expert-v2, hopper-medium-v2
      agent: edac,sac_n,rebrac
