agent_name: bpr
algorithm: unifloral_bpr
lr: 1e-3
actor_lr: 1e-3
lr_schedule: constant
batch_size: 1024
gamma: 0.99
polyak_step_size: 0.005
norm_obs: true
actor_num_layers: 3
actor_layer_width: 256
actor_ln: true
deterministic: false
deterministic_eval: true
use_tanh_mean: true
use_log_std_param: false
log_std_min: -5.0
log_std_max: 2.0
num_critics: 2
critic_num_layers: 3
critic_layer_width: 256
critic_ln: true
actor_bc_coef: 0.0
actor_q_coef: 0.0
use_q_target_in_actor: false
normalize_q_loss: false
aggregate_q: min
use_awr: false
awr_temperature: 1.0
awr_exp_adv_clip: 100.0
num_critic_updates_per_step: 2
critic_bc_coef: 0.0
diversity_coef: 0.0
policy_noise: 0.0
noise_clip: 0.0
use_target_actor: true
use_value_target: false
value_expectile: 0.7
use_entropy_loss: true
ent_coef_init: 1.0
actor_entropy_coef: 0.0
critic_entropy_coef: 1.0
use_bpr: true
bpr_lambda: 1.0
bpr_actor_coef: 1.0
behavior_energy_lr: 1e-3
behavior_energy_num_layers: 3
behavior_energy_layer_width: 256
behavior_energy_num_negatives: 16
behavior_energy_temperature: 1.0
behavior_energy_pretrain_steps: 100000
