agent_name: mobrac
algorithm: unifloral_mobrac
num_updates: 1000000
eval_interval: 2500
eval_workers: 8
eval_final_episodes: 1000
log: true
wandb_project: unifloral
wandb_team: flair
wandb_group: debug
lr: 1e-3
actor_lr: 1e-3
lr_schedule: constant
batch_size: 1024
gamma: 0.99
polyak_step_size: 0.005
norm_obs: false
actor_num_layers: 3
actor_layer_width: 256
actor_ln: true
deterministic: true
deterministic_eval: false
use_tanh_mean: true
use_log_std_param: false
log_std_min: -5.0
log_std_max: 2.0
num_critics: 2
critic_num_layers: 3
critic_layer_width: 256
critic_ln: true
actor_bc_coef: 0.001
actor_q_coef: 1.0
use_q_target_in_actor: false
normalize_q_loss: true
aggregate_q: min
use_awr: false
awr_temperature: 1.0
awr_exp_adv_clip: 100.0
num_critic_updates_per_step: 2
critic_bc_coef: 0.01
diversity_coef: 0.0
policy_noise: 0.2
noise_clip: 0.5
use_target_actor: true
use_value_target: false
value_expectile: 0.8
use_entropy_loss: false
ent_coef_init: 1.0
actor_entropy_coef: 0.0
critic_entropy_coef: 0.0
model_path: PLACEHOLDER MODEL PATH
dataset_sample_ratio: 0.05
rollout_interval: 1000
rollout_length: 5
rollout_batch_size: 50000
model_retain_epochs: 5
step_penalty_coef: 0.5
