agent_name: td3_bc
algorithm: unifloral_td3_bc
num_updates: 1000000
eval_interval: 2500
eval_workers: 8
eval_final_episodes: 1000
log: true
wandb_project: unifloral
wandb_team: flair
wandb_group: debug
lr: 3e-4
actor_lr: 3e-4
lr_schedule: constant
batch_size: 256
gamma: 0.99
polyak_step_size: 0.005
norm_obs: true
actor_num_layers: 2
actor_layer_width: 256
actor_ln: false
deterministic: true
deterministic_eval: false
use_tanh_mean: true
use_log_std_param: false
log_std_min: -5.0
log_std_max: 2.0
num_critics: 2
critic_num_layers: 2
critic_layer_width: 256
critic_ln: false
actor_bc_coef: 1.0
actor_q_coef: 2.5
use_q_target_in_actor: false
normalize_q_loss: true
aggregate_q: first
use_awr: false
awr_temperature: 1.0
awr_exp_adv_clip: 100.0
num_critic_updates_per_step: 2
critic_bc_coef: 0.0
diversity_coef: 0.0
policy_noise: 0.2
noise_clip: 0.5
use_target_actor: true
use_value_target: false
value_expectile: 0.8
use_entropy_loss: false
ent_coef_init: 1.0
actor_entropy_coef: 0.0
critic_entropy_coef: 0.0
