agent_name: td3_awr
algorithm: unifloral_td3_awr
actor_bc_coef: 0.001
normalize_q_loss: true
use_awr: true
awr_temperature: 3.0
num_critic_updates_per_step: 2
critic_bc_coef: 0.01
policy_noise: 0.2
noise_clip: 0.5
use_target_actor: true
